### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by norgeindian** [auroraextensions/simplereturns#1]
It would be great if a new version tag could be published, to make this great module usable in a current composer environment.
Currently, the latest published version (1.1.1) requires `magento/framework: 102.*.*`.
These framework versions require PHP 7.2 or even PHP 7.1.3.
So the module can not be installed if using PHP 7.3 or 7.4.

**Comment by nickolasburr** [comment]
@norgeindian Thanks for the feedback, I greatly appreciate it. I've published v1.2.0 to add support for Magento 2.4, which should resolve this issue.

https://github.com/auroraextensions/simplereturns/releases/tag/1.2.0
