### ISSUE TITLE
Breaks Reorder Link in M 2.4.2

### ISSUE THREAD

**Issue by TomJ1588** [auroraextensions/simplereturns#2]
[auroraextensions/simplereturns/view/frontend/templates/customer/account/recent.phtml](https://github.com/auroraextensions/simplereturns/blob/master/view/frontend/templates/customer/account/recent.phtml)

#71 - changed data-post="" (double quote - escapes) to data-post='' (single quote - no escape)

escaping the link breaks the data-post element and stops it from working, throwing JS errors in the console.

**Comment by nickolasburr** [comment]
@TomJ1588 This issue is fixed in d52faad and will be included in the next release.

**Comment by nickolasburr** [comment]
Resolved as of v1.3.0
